# Generated by Django 4.2.6 on 2023-10-27 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Togri_soz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soz', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Notogri_soz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soz', models.CharField(max_length=30)),
                ('togri_soz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.togri_soz')),
            ],
        ),
    ]
