# Generated by Django 4.2.6 on 2023-10-27 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notogri_soz',
            new_name='Notogri',
        ),
        migrations.RenameModel(
            old_name='Togri_soz',
            new_name='Togri',
        ),
        migrations.RenameField(
            model_name='notogri',
            old_name='togri_soz',
            new_name='t_soz',
        ),
    ]
